Product list
theVivek-kumar/Ecommerce-Major-project-neog pull request #6
Opened 2022-02-17 22:50 UTC by Vivek-jpg

![image](https://user-images.githubusercontent.com/57774129/154584230-bcd5281c-f4fe-4389-a32c-7e0ea3eee567.png)
![image](https://user-images.githubusercontent.com/57774129/154584327-38e4fa99-2998-4776-a408-6a5c478c7e6b.png)
![image](https://user-images.githubusercontent.com/57774129/154584384-7283b265-8b2f-412a-b292-5041163476e0.png)
![image](https://user-images.githubusercontent.com/57774129/154584421-4af5f9e0-c08a-4f30-a3e9-65a1dbb58d23.png)
![image](https://user-images.githubusercontent.com/57774129/154584475-6ca6b7fa-ba70-4c78-b075-69504c136aeb.png)
![image](https://user-images.githubusercontent.com/57774129/154584523-5fb831d6-e920-4430-9d08-266293aae95f.png)

2022-02-17 23:59 UTC, eldhoabraham94 approved these changes
Seems good to go

2022-02-18 12:15 UTC, Adarsh-Patel-Dev requested changes

2022-02-18 12:15 UTC, Adarsh-Patel-Dev commented on my-cart/product-list/product.css
> +
remove extra spaces

2022-02-18 12:15 UTC, Adarsh-Patel-Dev commented on my-cart/product-list/product.css
> +    color: va;
What is va here?

2022-02-18 12:15 UTC, Adarsh-Patel-Dev commented on my-cart/product-list/product.html
> +                        1k</p> <p>
use proper formatting here

2022-02-18 17:51 UTC, Adarsh-Patel-Dev approved these changes

2022-02-18 19:06 UTC, merged