Log out
theVivek-kumar/Ecommerce-Major-project-neog pull request #7
Opened 2022-02-18 20:56 UTC by Vivek-jpg

![image](https://user-images.githubusercontent.com/57774129/154760069-7a470e3e-d76f-4c21-80c1-883181fc58ee.png)

2022-02-19 10:41 UTC, Adarsh-Patel-Dev requested changes

2022-02-19 10:41 UTC, Adarsh-Patel-Dev commented on log-out/log-out.html
> +
remove extra spaces

2022-02-19 10:44 UTC, Adarsh-Patel-Dev requested changes

2022-02-19 10:44 UTC, Adarsh-Patel-Dev commented on style.css
> +     background-color: rgb(255, 255, 255);
use color variables

2022-02-19 17:19 UTC, sharmayatendra commented on style.css
>      --PRIMERY-color : rgb(12, 109, 165);
just a small suggestion "primary" spelling mistake & try to be consistent since you haven't used block letters for variables try to use small letters here as well.

2022-02-19 17:20 UTC, sharmayatendra commented on style.css
> +     --text-color-login-btn:#140330;
either use RGB or hex-code don't combine both.

2022-02-19 17:22 UTC, sharmayatendra commented on style.css
> +     margin: .3rem;
you can directly use px values rather than rem since it's less than 10px.

2022-02-19 17:22 UTC, sharmayatendra commented on style.css
> +     border-radius: 30px;
you can use rem here

2022-02-19 17:23 UTC, sharmayatendra approved these changes
good work can look upon suggested changes.

2022-02-19 20:39 UTC, merged

2022-02-20 00:33 UTC, govindappaarun reviewed
Please fix some of them, as they are important

2022-02-20 00:33 UTC, govindappaarun commented on log-out/log-out.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Merriweather:wght@300&family=Montserrat:wght@100;300;500;700;900&family=Zen+Antique&family=Zen+Kurenaido&display=sw
have you used this font anywhere, and why import this file just for logout?

2022-02-20 00:33 UTC, govindappaarun commented on log-out/log-out.css
> +    justify-content: center;;
remove an extra colon

2022-02-20 00:33 UTC, govindappaarun commented on log-out/log-out.css
> +.log-out-container-body-btn{
Its more descriptive, limit multi word selector name to 3 or 4 words max, use descendant selector instead

2022-02-20 00:33 UTC, govindappaarun commented on log-out/log-out.html
> +                <i class='fa fa-heart' style='color: rgb(255, 0, 0)'></i>
avoid inline style

2022-02-20 00:38 UTC, govindappaarun commented on log-out/log-out.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Merriweather:wght@300&family=Montserrat:wght@100;300;500;700;900&family=Zen+Antique&family=Zen+Kurenaido&display=sw
Your UI has needs set of improvements, please have a one to one review with someone  for more feedback and improvement suggestions